mail:
    from: "me@example.com"
    to: "you@example.com"
# see https://github.com/andris9/nodemailer-smtp-transport#usage
smtp:
    host: "smtp.gmail.com"
    port: 25
# Events list:
# - restart
# - delete
# - stop
# - restart overlimit
# - exit
# - start
# - online
events:
    - exit
template: './template.md'
# this is the email subject
subject: '[<%= hostname %>] Error Report'
#wait for 10 seconds before sending an email - avoid spam
polling: 10000
#attach your process logs to the email
attach_logs: true 
